[package]
name = "ConsoleBreakout"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"
crossterm = "0.19.0"
colored = "2.1.0"
winapi = "*"
user32-sys = "*"
kernel32-sys = "*"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros", "time"] }
