[package]
name = "ConsoleBreakout"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"
crossterm = "0.19.0"
colored = "2.1.0"
winapi = "*"
user32-sys = "*"
keylogger = "0.2.1"
kernel32-sys = "*"